version: '3.8'
services:
  # chatbotapi:
  #   build: ./server/ChatbotAPI
  #   ports:
  #     - "5000:80"
  #     - "4020:4020"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     # - OPENAI_API_KEY=your_openai_api_key_here
  #     # Add other environment variables as needed
  #   depends_on:
  #     - qdrant
  #   volumes:
  #     - ./server/ChatbotAPI/UploadedPdfs:/app/UploadedPdfs

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
